# --- Estágio 1: Build Go ---
FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/f1-collector /app/src/

# --- Estágio 2: Imagem Final Go ---
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/f1-collector .
EXPOSE 20777/udp
CMD ["./f1-collector"]
